### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by Unsuriati** [maenDisease/Float#2]
channel list no longer collapsing this morning, I've reinstalled vencord multiple times, perused the css with my limited knowledge and no clue whats going on.

**Comment by doofsoup** [comment]
I think a large, recent update broke the functionality again? Edit: posted this right as the update was pushed. Thank you so much for float!

**Comment by mvidelatraduc** [comment]
This started happening to me too, reinstalling didn't solve it.

![imagen](https://github.com/user-attachments/assets/a8ad1812-cb91-4b88-a690-39dd075469b6)

**Comment by kyleung271** [comment]
The base css added a important modifier in the width.
Seems adding important modifier in the theme css can make it work again?

```css
#app-mount .app_bd26cc .sidebar_a4d4d9 {
  position: absolute;
  z-index: 101;
  height: 100%;
  width: -moz-fit-content;
  width: fit-content;
  width: -moz-fit-content !important;
  width: fit-content !important;
  transition: width var(--sidebar-transition-exit);
}
```
